site_name: DAZSER
site_url: https://dazser.github.io/docs/
repo_url: https://github.com/dazser/docs/
site_author: Kyle McNally
copyright: "2021"
theme:
  name: readthedocs
  custom_dir: overrides/
  logo: docs/crown.png
plugins:
  - search
  - git-revision-date-localized
  - macros
